import type { Product, ProductData } from "@/types";

const reviews = [
  {
    author: "@minji_glow",
    country: "미국",
    rating: 5,
    text: "다음 날 피부가 더 밝아 보였고, 한국에서 전 세계 무료배송으로 받아볼 수 있어 편했어요.",
  },
  {
    author: "Sarah K.",
    country: "캐나다",
    rating: 5,
    text: "가볍고 들뜸이 없었어요. 배송비가 포함되어 있어서 구매 결정이 쉬웠습니다.",
  },
];

const shippingCountries = ["미국", "캐나다", "호주", "싱가포르", "영국", "일본", "독일"];

const heartleaf: Product = {
  id: "jbm-heartleaf",
  brand: "저스트비미",
  name: "어성초 리바이탈 에너지 톤업 크림",
  imageType: "green-tea",
  discountRate: 30,
  priceUSD: 22.97,
  originalPriceUSD: 32.97,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["톤업", "진정", "수분 공급"],
  ingredients: ["어성초 추출물", "병풀 추출물", "나이아신아마이드"],
  goodFor: ["칙칙함", "민감성 피부", "복합성 피부"],
  photos: [],
  bestFor: ["칙칙함", "민감성 피부", "복합성 피부"],
  description: "어성초 성분으로 피부를 편안하게 가꾸고 맑은 톤을 더하는 데일리 톤업 크림입니다.",
  howToUse: "아침과 저녁 세안 후 진주알 크기만큼 덜어 피부에 고르게 펴 발라주세요.",
  rating: 4.9,
  reviewCount: 1240,
  reviewSnippets: reviews,
  shippingCountries,
  estimatedDelivery: "5-11일",
  shippingFeeText: "전 세계 무료배송 포함",
};

const cica: Product = {
  id: "jbm-cica",
  brand: "저스트비미",
  name: "시카 카밍 다운 수딩 세럼",
  imageType: "cucumber",
  discountRate: 25,
  priceUSD: 19.5,
  originalPriceUSD: 26.0,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["진정", "장벽 케어", "수분 공급"],
  ingredients: ["시카", "마데카소사이드", "판테놀"],
  goodFor: ["민감성 피부", "자극받은 피부", "복합성 피부"],
  photos: [],
  bestFor: ["민감성 피부", "자극받은 피부", "복합성 피부"],
  description: "자극받은 피부를 편안하게 다독이는 가벼운 시카 진정 세럼입니다.",
  howToUse: "아침과 저녁 크림 전 단계에서 피부결을 따라 부드럽게 흡수시켜 주세요.",
  rating: 4.8,
  reviewCount: 612,
  reviewSnippets: reviews,
  shippingCountries,
  estimatedDelivery: heartleaf.estimatedDelivery,
  shippingFeeText: heartleaf.shippingFeeText,
};

const riceGlow: Product = {
  id: "jbm-rice",
  brand: "저스트비미",
  name: "라이스 글로우 데일리 에센스",
  imageType: "rice",
  discountRate: 24,
  priceUSD: 24.4,
  originalPriceUSD: 32.0,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["브라이트닝", "글래스 스킨", "수분 공급"],
  ingredients: ["쌀 추출물", "나이아신아마이드", "히알루론산"],
  goodFor: ["건성 피부", "칙칙함", "글래스 스킨"],
  photos: [],
  bestFor: ["건성 피부", "칙칙함"],
  description: "한국 쌀뜨물에서 영감을 받은 촉촉한 광채 에센스입니다.",
  howToUse: "세안 후 세럼 전 단계에서 손바닥으로 가볍게 눌러 흡수시켜 주세요.",
  rating: 4.9,
  reviewCount: 980,
  reviewSnippets: reviews,
  shippingCountries,
  estimatedDelivery: heartleaf.estimatedDelivery,
  shippingFeeText: heartleaf.shippingFeeText,
};

const glassMist: Product = {
  id: "jbm-glass-mist",
  brand: "저스트비미",
  name: "글래스 스킨 하이드라 미스트 120ml",
  imageType: "custom",
  discountRate: 24,
  priceUSD: 16.8,
  originalPriceUSD: 22.0,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["수분 공급", "글래스 스킨", "쿨링"],
  ingredients: ["히알루론산", "판테놀", "녹차"],
  goodFor: ["건성 피부", "복합성 피부", "글래스 스킨"],
  photos: [],
  bestFor: ["건성 피부", "복합성 피부"],
  description: "피부가 건조할 때 즉각적으로 수분감을 더하는 가볍고 맑은 미스트입니다.",
  howToUse: "피부가 건조할 때 얼굴에서 20cm 정도 떨어뜨려 가볍게 분사해 주세요.",
  rating: 4.7,
  reviewCount: 421,
  reviewSnippets: reviews,
  shippingCountries,
  estimatedDelivery: heartleaf.estimatedDelivery,
  shippingFeeText: heartleaf.shippingFeeText,
};

export const justBeMeData: ProductData = {
  brandName: "저스트비미",
  slug: "just-be-me",
  link: "klow.kr/just-be-me",
  category: "스킨케어",
  settlementKRW: 0,
  exchangeRate: 1350,
  shippingUSD: 20,
  paymentFeeRate: 0.15,
  products: [heartleaf, cica, riceGlow, glassMist],
};
