import type { Product, ProductData } from "@/types";

const reviews = [
  {
    author: "@minji_glow",
    country: "USA",
    rating: 5,
    text: "Skin looks brighter the next morning. Worth shipping from Korea.",
  },
  {
    author: "Sarah K.",
    country: "Canada",
    rating: 5,
    text: "Light, no white cast, and the shipping was actually flat $15.",
  },
];

const heartleaf: Product = {
  id: "jbm-heartleaf",
  brand: "Just Be Me",
  name: "Heartleaf Revital Energy Tone-Up Cream",
  imageType: "green-tea",
  discountRate: 30,
  priceUSD: 22.97,
  originalPriceUSD: 32.97,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["Tone up", "Soothing", "Hydration"],
  ingredients: ["Heartleaf Extract", "Centella Asiatica", "Niacinamide"],
  bestFor: ["Dull", "Sensitive", "Combination"],
  description:
    "A daily Korean tone-up cream with heartleaf for soothed, glowing skin.",
  howToUse:
    "Apply on cleansed skin morning and night. A pearl-sized amount is enough.",
  rating: 4.9,
  reviewCount: 1240,
  reviewSnippets: reviews,
  shippingCountries: [
    "United States",
    "Canada",
    "Australia",
    "Singapore",
    "United Kingdom",
    "Japan",
    "Germany",
  ],
  estimatedDelivery: "7–12 days",
  shippingFeeText: "Flat $15 global shipping",
};

const cica: Product = {
  id: "jbm-cica",
  brand: "Just Be Me",
  name: "Cica Calm Down Soothing Serum",
  imageType: "cucumber",
  discountRate: 25,
  priceUSD: 19.5,
  originalPriceUSD: 26.0,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["Soothing", "Barrier care", "Hydration"],
  ingredients: ["Cica", "Madecassoside", "Panthenol"],
  bestFor: ["Sensitive", "Irritated", "Combination"],
  description:
    "A lightweight calming serum with cica complex for stressed-out skin.",
  howToUse: "Use morning and night before moisturizer.",
  rating: 4.8,
  reviewCount: 612,
  reviewSnippets: reviews,
  shippingCountries: heartleaf.shippingCountries,
  estimatedDelivery: heartleaf.estimatedDelivery,
  shippingFeeText: heartleaf.shippingFeeText,
};

const riceGlow: Product = {
  id: "jbm-rice",
  brand: "Just Be Me",
  name: "Rice Glow Daily Essence",
  imageType: "rice",
  discountRate: 24,
  priceUSD: 24.4,
  originalPriceUSD: 32.0,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["Brightening", "Glass skin", "Hydration"],
  ingredients: ["Rice Extract", "Niacinamide", "Hyaluronic Acid"],
  bestFor: ["Dry", "Dull"],
  description: "A glow-boosting essence inspired by traditional Korean rice water.",
  howToUse: "Pat into clean skin before serum.",
  rating: 4.9,
  reviewCount: 980,
  reviewSnippets: reviews,
  shippingCountries: heartleaf.shippingCountries,
  estimatedDelivery: heartleaf.estimatedDelivery,
  shippingFeeText: heartleaf.shippingFeeText,
};

const glassMist: Product = {
  id: "jbm-glass-mist",
  brand: "Just Be Me",
  name: "Glass Skin Hydra Mist 120ml",
  imageType: "custom",
  discountRate: 24,
  priceUSD: 16.8,
  originalPriceUSD: 22.0,
  settlementKRW: 0,
  costKRW: 0,
  marginKRW: 0,
  benefits: ["Hydration", "Glass skin", "Cooling"],
  ingredients: ["Hyaluronic Acid", "Panthenol", "Green Tea"],
  bestFor: ["Dry", "Combination"],
  description: "A glassy, weightless mist for an instant hydration reset.",
  howToUse: "Mist 20cm from the face whenever skin feels dry.",
  rating: 4.7,
  reviewCount: 421,
  reviewSnippets: reviews,
  shippingCountries: heartleaf.shippingCountries,
  estimatedDelivery: heartleaf.estimatedDelivery,
  shippingFeeText: heartleaf.shippingFeeText,
};

export const justBeMeData: ProductData = {
  brandName: "Just Be Me",
  slug: "just-be-me",
  link: "klow.kr/just-be-me",
  category: "Skincare",
  settlementKRW: 0,
  exchangeRate: 1350,
  shippingUSD: 15,
  paymentFeeRate: 0.05,
  products: [heartleaf, cica, riceGlow, glassMist],
};
